spring.application.name=moviecollection

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_collection
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


tmdb.api.key=20163e0cf4bf388db01a7321430ba2cd

server.address=0.0.0.0